### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by chrisgatesuk** [t3rmin8tor/pilfer-installer#10]
t3rmin8tor,

NapoleonWils0n pointed me to yourself regarding the following problems I have had installing your pilfer-installer on my machines:

I uninstalled rip-record on my laptop earlier and all associated programs including playercorefactory. Everything seems to be working fine apart from:

When I try to record using the pilfer GUI using a timestamp, it brings up a CMD window titled C:.
This window disappears withing 1/2 second and nothing happens. The same thing happens when trying to schedule a recording using the GUI.
When I try to record without a duration it works fine.
The laptop is running windows 10.

As a second problem, I also tried to upgrade this on my desktop computer but this has not worked at all. When I try to record from Kodi it brings up the following windows directory:
C:\Users\Chris
This contains only 1 file: mpv.conf
Nothing else happens.
This machine is running Windows 7.

Any ideas on either problem? Your help would be greatly appreciated. Please let me know if your require any further information.

Cheers,

Chris.

**Comment by t3rmin8tor** [comment]
hi chris  first of all i must  apologise for  not responding sooner  i have not been active  for several months due to personal issues with health 

today i released v3.0 of pilfer  as there were issues with windows 10 uodates not playing nice with pilfer
<a href="https://github.com/t3rmin8tor/pilfer-installer/releases/download/v3.0/pilfer-install-v3.0.exe">pilfer-v3.0</a>
first thing is can you give me the full path to where pilfer is installed on your system?
it should be c:\pilfer  this is critical as any other install location will NOT work and will cause the issues you describe because environment paths will not match (e.g the system will be looking for  dependencies in one location) however if you change the install path of pilfer it would never find the files in the default location and the program will never work

**Comment by chrisgatesuk** [comment]
t3rmin8tor
Thanks for getting back to me. Sorry it's taken so long for me to respond. I have now managed to get this all working thanks to your update and hard work. Very much appreciated!
Two questions (that may or may not have already been answered in the past - apologies if so):
1. Can I change the recording directory (for example to an external NAS drive)?
2. I don't seem to be able to schedule recordings or play streams from Pilfer GUI. A black window (like a CMD window) pops up briefly and then disappears. What format should both the Channel and Duration be in? My channel format looks like this:\
http://uranustv.net:25461/c**********k@h**mail.com/H********K/62414
where the missing (*) are username and password of my IPTV provider.

Any help would be greatly appreciated.

Regards,

Chris.

**Comment by t3rmin8tor** [comment]
hi chris 

did you configure pilfer by going to the config tab and clicking the configure pilfer button
this is a critical step as it grabs the latest recording services files 

as for the recording path if you can give me path to the exact location of where you need recordings to be stored i may be able to write a customised gui that will allow you to move completed recordings from the desktop to the required location
unfortunately it is not possible to modify the default recording path without completely re writing a huge chunk of code 

i hope this helps

**Comment by chrisgatesuk** [comment]
Thanks for getting back to me so promptly. Your help is, as ever, greatly appreciated. I did click the configure Pilfer button and everything works within Kodi (recordings, playing through external player, saving URL, etc) but I can’t get a schedule to record properly. I am copying the channel directly from the saved URL that comes from Kodi and putting the time format as hh:mm:ss
The date format I have played around with 11 03 2019 or 03 11 2019, etc
Not sure what I’m doing wrong?

As for my directory I’m looking to save it to S:\Complete   (This is my NAS drive). Not worth re-writing code for though mate. I can easily move files myself!

One other question. There are a couple of PC’s that I have tried to install this manually on. I have uninstalled RipRecord as mentioned but it leaves behind many other “bits” (eg ffmpeg, rtmpdump and perhaps the environment directories). When I try to install using your tool it doesn’t give me any desktop icons for Pilfer, etc. What else to I need to delete to be able to give me a “fresh install” using your tool?

Thanks again and kind regards,

Chris.

**Comment by t3rmin8tor** [comment]
hi chris  thanks for your detailed feedback 

i have looked into the issue of  the schedules failing to record there seems to be a bug in the code that is causing this function to fail and i am working on a solution to this and i can confirm that the issue is not caused by anything that you are doing wrong 

as for the directory location to move completed recordings to your NAS drive 

feel free to edit the pilfer.pyw file look for line 55 

55 def library():
56	os.system('move ' + str(record_path) + '*.mkv C:\\pilfer\\system\\videos\\')

edit line 56 to
os.system('move ' + str(record_path) + '*.mkv S:\\Complete\\')

as for environment variables on other computers 
to completely remove pilfer or the old riprecord settings from the systems 

1 go to system
2 goto advanced settings
3 goto environment settings
4 edit the path line winthin the user variables 
5 delete all and only all references to
 pilfer  and python FOR PILFER INSTALATIONS

riprecord bash git 

the only variables that should not be removed if they exist are  one drive or any references to microsoft applications
